Milestone: Todo list project
dasileker/To-do-list pull request #2
Opened 2021-03-09 16:42 UTC by newhorizon-tech

This is a mini-project that allows you to :

- Create new tasks for a to-do list
- Display the current tasks in the todo list
- Display different projects(categories)
- Modify an existing task
- Delete a task from the list 

The project utilizes :

- Factory pattern
- DOM manipulation 
- LocalStorage
- ES6 Arrow functions 
- Functions like map and filter 
- ES6 Modules 
- Module and stylesheets bundling

2021-03-09 17:53 UTC, addod19 requested changes
## Status: Require changes :recycle: :trophy: 

Hi @newhorizon-tech and @dasileker, congratulations on this project :muscle: The README file is professional, commit messages easy to understand, PR is detailed with information :slightly_smiling_face: Let us kindly address the comments below so we can move ahead:

- The task should also be an object, currently I cannot see it declared as an object
- Kindly update the scripts as in the comments below
- Kindly remove all commented codes

[Optional]
- Kindly add basic validations so a user cannot submit empty data which could be expensive for our application

Once these are fixed, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-03-09 17:53 UTC, addod19 commented on src/display.js
> +      // const testBtn = document.createElement('button');
Kindly delete commented code, use git history instead

2021-03-09 17:53 UTC, addod19 commented on src/display.js
> +      // }
Kindly delete commented code, use git history instead

2021-03-09 17:53 UTC, addod19 commented on src/display.js
> +      // loose.addEventListener('onclick', deleteItem);
Kindly delete commented code, use git history instead

2021-03-09 17:53 UTC, addod19 commented on src/index.js
> +// };
Kindly delete commented code, use git history instead

2021-03-09 17:53 UTC, addod19 commented on src/index.js
> +// let listElement = [];
Kindly delete commented code, use git history instead

2021-03-09 17:53 UTC, addod19 commented on src/styles.scss
> +  // margin-right: 20px;
Kindly delete commented code, use git history instead

2021-03-09 17:53 UTC, addod19 commented on package.json
> +  },
Kindly update the script so we can run commands like npm build, dev or start
```
 "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
```

2021-03-10 10:52 UTC, newhorizon-tech commented
We made the following changes: 

- Added NPM scripts 
- Improved project styling 
- Added validation

2021-03-10 18:08 UTC, Spayco approved these changes
# Project Approved

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-03-10 18:14 UTC, merged